### ISSUE TITLE
Parameters not autocompleted

### ISSUE THREAD

**Issue by firegore2** [php-integrator/atom-autocompletion#101]
When I try to autocomplet my code it show the function with their parameters,
![image](https://cloud.githubusercontent.com/assets/23504988/26604746/95568584-458b-11e7-92b8-79750e518804.png)
but if I press tab button it writte only the function without parameters:
![image](https://cloud.githubusercontent.com/assets/23504988/26604785/b995394a-458b-11e7-8901-781ac2de2cd0.png)

How can I solve this problem?

**Comment by Gert-dev** [comment]
Hello! This is in fact by design, see also #92.
