### ISSUE TITLE
Not showing classes in project.

### ISSUE THREAD

**Issue by mikebronner** [php-integrator/atom-autocompletion#104]
After indexing, I am not seeing some classes defined elsewhere in my project. Observing this a bit more, there appears to a substantial number of random classes missing from autocomplete, both from the project, as well as from 3rd-party packages.

**Comment by Gert-dev** [comment]
Please take a look at https://github.com/php-integrator/atom-base/issues/314, which is also about classes being missing from the index. Perhaps the suggestions there will help you fix the issue or, if not, help figure out why this is happening.
