### ISSUE TITLE
After a moment, completion does not  work.

### ISSUE THREAD

**Issue by oknixus** [php-integrator/atom-autocompletion#105]
It works fine when I run atom every time.
But after a moment, sometimes a few minutes, sometimes hours, completion does not display anything.
Then I have to rerun the atom, great, everything is ok. But after a while, It dose not work again.
And I have to rerun it again.

My Env:
macOS High Sierra v10.13
Atom v1.21.0
php-integrator-base v3.0.1
php-integrator-autocomplete-plus v1.6.0

What do I need to do form fixing it ?

**Comment by Gert-dev** [comment]
When that happens, can you open the developer tools and see if there are any errors listed there?

Apart from that, when this happens, is the indexing progress bar perhaps displaying in the bottom right?

**Comment by oknixus** [comment]
No errors and indexing progress has completed.

**Comment by Gert-dev** [comment]
This is a very strange issue. You have no other packages installed besides the ones listed?

What you could try is, when this happens, opening up the developer tools and diving into the php-integrator-autocompletion package sources with a debugger and seeing if it still enters any of the providers, e.g. `ClassProvider` or `GlobalFunctionProvider`.

**Comment by Gert-dev** [comment]
Closing this due to its age and staleness. Feel free to open a new issue if this still occurs.
