### ISSUE TITLE
Does not disable suggestions from ide-php

### ISSUE THREAD

**Issue by andrews05** [php-integrator/atom-autocompletion#106]
I use ide-php primarily for its Hover functionality but it also provides auto-completion which is NOT disabled by php-integrator, so I end up with double-ups. It would be really nice if php-integrator could work well with the atom-ide-ui.

**Comment by Gert-dev** [comment]
I don't think this is something we can, at least definitively, fix. What the "Disable builtin autocompletion" flag does currently is cause autocomplete-plus to exclude suggestions from other providers with a lower priority than the one from this package. In theory that means I could fix it by upping the priority, but if other packages decide to up their priority for whatever reason, it will break again. Also, if you *did* want to use some other autocompletion package along with this one, it would also get filtered out.

The best thing to do would be to ask the author of the other package, in this case `ide-php`, to add a checkbox that disables the autocompletion functionality of said package. You can already disable php-integrator-autocomplete-plus to do the same for php-integrator. Also, `atom-ide-ui` already plays well with php-integrator, it's just that most specific `ide-*` packages assume they are the only one running for their respective language 😄.
