### ISSUE TITLE
static and self in non-static contexts.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-autocompletion#45]
`static` and `self` behave mostly like `$this` in **non-static** contexts, i.e. they can also access non-static members. This is a very low priority item, but we should get this done at some point.
##

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in the core. [A new issue for this ticket has been created in the core](https://gitlab.com/php-integrator/core/issues/161).
