### ISSUE TITLE
Use statements with alias are not suggested in the class list.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-autocompletion#46]
``` php
use A\B as Foo;

F // Foo is not suggested.
```

We should probably implement passing a filename to getClassList so a class list specific for that file is returned. (This, however, will have implications for the cacheability of the class list.)
##

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.

[A new issue for this ticket has been created in the core](https://gitlab.com/php-integrator/core/issues/162).
