### ISSUE TITLE
Add use statements for namespaced constants when autocompleting them

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-autocompletion#70]

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.

[A new issue for this ticket has been created in the core](https://gitlab.com/php-integrator/core/issues/163).
