### ISSUE TITLE
Add use statements for namespaced functions when autocompleting them

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-autocompletion#71]

**Comment by infomaniac50** [comment]
Does this affect ``use function`` in php-integrator-linter as well? I'm getting one warning and one error for each function I import.

```plain
php-integrator-linter Error The global function map was not found. at line 16 col 16
php-integrator-linter Warning Functional\map is not used anywhere. at line 4 col 14
```

I'm using https://github.com/lstrojny/functional-php with PHP 5.6 and functional-php recommends the use function statement on 5.6.

**Comment by Gert-dev** [comment]
Not directly, since this is only about the client side (CoffeeScript) part of doing this. But I _think_ this is indeed a bug in the base package. I've created a ticket about it here [1].

[1] https://github.com/php-integrator/atom-base/issues/245

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.

[A new issue for this ticket has been created in the core](https://gitlab.com/php-integrator/core/issues/164).
