### ISSUE TITLE
Namespace statement namespace suggestions

### ISSUE THREAD

**Issue by pszczekutowicz** [php-integrator/atom-autocompletion#74]
Hi, 

Currently when developer gets suggestions after namespace keyword list contains snippets, functions, classes, interfaces (both FQCN) and keywords and it does not have list of available namespaces defined so far in project. I guess that it may be nice feature to have such list at beginning. The perfect solution that comes to mind is namespace from other files in same directory as first entry - assuming that files/namespaces in directories follow PSR{0,4}.

**Comment by Gert-dev** [comment]
I can suggest the known namespaces after the `namespace` keyword and I can look into deducing the relevant namespace name based on the directory and PSR-0/PSR-4 namespace prefixes.

I can also try disabling things such as global function and constant suggestions after the `namespace` keyword. Sadly, this will be limited to the suggestions provided by this package, as some snippets are provided by `language-php` itself and I don't think these can be easiliy disabled (autocompletion suggestions from that package are already disabled whenever this package is enabled).

I think this idea will also fit well in the refactoring package, allowing you to do something like `alt-enter` → `Generate Namespace` based on the current folder (in the case of PSR-0 or PSR-4).

**Comment by pszczekutowicz** [comment]
Thank you for answer. I played yesterday with https://github.com/php-integrator/core and I created **--namespaces-list** command simple returning array of namepsaces available in project. If you do not mind I'll create PR.

**Comment by Gert-dev** [comment]
That's nice to hear, it would indeed be useful and would save me some time as soon as I get to implementing this feature in its entirety.

**Comment by Gert-dev** [comment]
Thanks for the PR, this should now be working in 1.2!
