### ISSUE TITLE
Unable to autocomplete abstract classes

### ISSUE THREAD

**Issue by fbourigault** [php-integrator/atom-autocompletion#77]
When autocompleting after the extends keyword, abstract classes are not proposed.

```php
<?php
namespace Ouverture\Bundle\FixturesBundle\DependencyInjection;

class OuvertureFixturesExtension extends Extension
{
}
```

I expect to have [`Symfony\Component\HttpKernel\DependencyInjection\Extension`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DependencyInjection/Extension.php) in the list but it's not provided. Moreover the `Symfony\Component\HttpKernel\DependencyInjection\Extension` [parent](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Extension/Extension.php) class (`Symfony\Component\DependencyInjection\Extension\Extension`) is also not provided.

**Comment by Gert-dev** [comment]
Do you happen to have another class in your codebase with the name `Extension`, but in another namespace? If yes, you are most likely a victim of (most annoying) bug #15.

**Comment by fbourigault** [comment]
Yes, I'm a #15 victim.
