### ISSUE TITLE
When enabled, breaks entries in snippets.cson

### ISSUE THREAD

**Issue by croaker000** [php-integrator/atom-autocompletion#78]
When this packaged is enabled entries in Atom Setting's snippets.cson are not parsed.

To duplicate, go to Atom Settings, open config folder by clicking the button, edit the snippets.cson and add a snippet.

With this plugin enabled, the snippet cannot be called. With it disabled, the snippet works.

**Comment by Gert-dev** [comment]
That's very strange, this package should not interfere with snippets. In fact, I've been using custom snippets along with this package since the start, e.g.:

```php
'.source.php':
    'Public method':
        'prefix': 'pubf'
        'body': """
            public function ${1:name}()
            {
                ${2:// TODO}
            }$0
        """
```

Could you post the prefix of the snippet you're trying to use? Perhaps there is a built-in snippet that is overriding yours?

**Comment by croaker000** [comment]
```
'.text.html.php':
   'Pretty Debug Message':
     'prefix': 'pretty'
     'body': 'echo \'<pre>DEBUG:: \'.print_r($1,true).\'</pre>\';'
```
Swapping in "source.php" for "text.html.php" seems to have done the trick. Maybe I was using an old handle?

**Comment by Gert-dev** [comment]
Are you by any chance using Atom 1.11, a beta version of Atom or do you have any other PHP packages installed (except language-php and this package)? Perhaps one of them is conflicting somehow.

I tried your snippet, but with the `.source.php` handle (with a leading dot, not sure if that matters) and that seems to work:

![Screenshot](https://cloud.githubusercontent.com/assets/6823929/19318069/754ff82c-90a7-11e6-9443-81a72baf6509.png)

**Comment by croaker000** [comment]
Here's what I have enabled
Atom v1.10.2 (fresh install, 1 week old)
php-integrator-base 1.2.6
php-integrator-linter 1.2.1
php-integrator-tooltips 1.0.4
php-integrator-autocomplete-plus 1.1.5
language-php 0.37.2

autocomplete-atom-api 0.10.0
autocomplete-css 0.11.2
autocomplete-html 0.7.2
autocomplete-plus 2.31.1
autocomplete-snippets 1.11.0

file-icons 1.7.21
local-history 3.4.1
open-recent 5.0.0
tool-bar 1.0.1
too-bar-main 0.0.10

+ Core packages

**Comment by jwhulette** [comment]
When the autocomplete-plus is enabled, the core language-php package does not work.
![disabled](https://cloud.githubusercontent.com/assets/4930051/25282314/19a88968-267e-11e7-9a2c-a7213031d438.png)
![enabled](https://cloud.githubusercontent.com/assets/4930051/25282315/19a8ea3e-267e-11e7-86d0-6162a68a8c48.png)

**Comment by Gert-dev** [comment]
@croaker000 is this still an issue?

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.
