### ISSUE TITLE
Option per project for automatic use inserts

### ISSUE THREAD

**Issue by hultberg** [php-integrator/atom-autocompletion#79]
Ref #48 

Would like the config per project, instead of globally.

**Comment by Gert-dev** [comment]
Hmmm.. I hadn't thought of that. Good idea!

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.
