### ISSUE TITLE
Suggests for $this

### ISSUE THREAD

**Issue by sluchznak** [php-integrator/atom-autocompletion#80]
Hello. Is it a bug or feature?
<img width="591" alt="2016-11-23 15 06 14" src="https://cloud.githubusercontent.com/assets/4091442/20555932/cc9dee4c-b18e-11e6-81bd-4dc5dbb8fa34.png">

**Comment by Gert-dev** [comment]
Hello, it's sort of a bug in the sense that it's a limitation if a dependency. You can find more information in [1]. I'll close this since that ticket is essentially about the same thing.

[1] https://github.com/php-integrator/atom-base/issues/238
