### ISSUE TITLE
Can i sort by length use statements

### ISSUE THREAD

**Issue by damonto** [php-integrator/atom-autocompletion#82]
now
```
use App\xxx\xxxx;
use App\xxx;
use App\xxx\xx;
```

but i want :

```
use app\xxx;
use app\xxx\xx;
use app\xxx\xxxx;
```

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.
