### ISSUE TITLE
@method pointers

### ISSUE THREAD

**Issue by brad-jones** [php-integrator/atom-autocompletion#86]
Just an idea I had...

Currently to document magic methods brought in via `__call` & `__callStatic` we can add `@method` to the classes docblock. This is fine for a handful of methods but get's rather tedious for lots of of methods, potentially from different classes. You end up with a disconnect between the source method docblock and the `@method` tag.

My idea:

```php
/**
 * @method \Class\Name::methodName
 * @method \Class\Name->methodName
 * @method \Class\Name::*
 * @method \Class\Name->*
 */
```

The first token after the `@method` tag is a class name, followed by either a **"Scope Resolution Operator"** or a **"Object Operator"** denoting if we are importing a static method or an instance method. We make the assumption the method is public.

_If `__call[Static]` was doing something odd with reflection and calling private or protected methods then you would still need to add an `@method` tag for each of those such methods._

The idea is that now we have a pointer to the actual method that we then perform static analysis on. Now when a new parameter is added to such a method we don't have to remember to update the `@method` tag also.

Finally instead of a specific method name, one could use a wildcard to import all public static or instance methods from the class.

But again perhaps this is better served by implementing https://github.com/php-integrator/core/issues/10

PS. Where is the best place to post such issues, this repo or the core repo?

**Comment by Gert-dev** [comment]
Suggestions and brainstorming about things such as this are in my opinion certainly productive, however I think such an issue would be better suited for the PSR-5 issue list [1].

I have thought in the past about supporting unofficial things in docblocks, but seeing as there is already so much disconnect between docblocks in code bases and tooling [2], I'm trying to limit support to things that are officially documented in either the phpDocumentor implementation or, in rare cases, the (draft) PSR-5 standard.

To answer your final question, other issues of this type are indeed suited for the core repository, as it handles static analysis, but I don't expect Atom users to know the difference between the repositories (although it is always nice if they do 👍 ).

[1] https://github.com/phpDocumentor/fig-standards/issues
[2] https://github.com/php-integrator/core/wiki/The-Docblock-Problem-And-How-They-Are-Processed
