### ISSUE TITLE
Overlapping callouts

### ISSUE THREAD

**Issue by brad-jones** [php-integrator/atom-autocompletion#87]
See screenshot.

![image](https://cloud.githubusercontent.com/assets/2754772/21335333/2d9ed6e2-c6b2-11e6-9134-bb01e29d29da.png)

This is annoying, the suggestions should always be in front of any other callouts in my opinion.
Not a major issue, just a nice to fix.

**Comment by Gert-dev** [comment]
Completely agreed, see also here [1] for an explanation of why this is a bigger issue and not as easy to solve as it seems.

[1] https://github.com/php-integrator/atom-call-tips/issues/9

**Comment by Gert-dev** [comment]
I'll close this since a fix has been published in call-tips 1.2.1. If you still experience the issue, feel free to reply there. Thanks for taking the time to report this 👍 .
