### ISSUE TITLE
Autocomplete annotations attributes

### ISSUE THREAD

**Issue by danjaredg** [php-integrator/atom-autocompletion#88]
This package is awesome, is it possible support the auto completion for annotations attributes?, great work.

**Comment by Gert-dev** [comment]
Hello and thanks! Are you referring to annotation attributes such as these?

```php
/**
 * @Column(type="string" name="some_field")
 */
protected $someField;
```

That seems possible, as the attributes should correspond to the public properties in the annotation class. I'll mark this enhancement.

**Comment by haringsrob** [comment]
Maybe he means:
```
/** @var /path/class/bar $foo */
```

**Comment by haringsrob** [comment]
@Gert-dev strange I am not getting any suggestions there.. Anyway yes my example used the wrong one.

**Comment by Gert-dev** [comment]
@haringsrob If this seems to be a bug, feel free to create a new ticket about it (either here, the base package or in the core). I would answer in this ticket, but I have to stop myself from doing that to prevent cluttering yet another ticket with an unrelated issue :-).

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.

[A new issue for this ticket has been created in the core](https://gitlab.com/php-integrator/core/issues/165).
