### ISSUE TITLE
Add suggestion for PHPMD annontation

### ISSUE THREAD

**Issue by hultberg** [php-integrator/atom-autocompletion#90]
Hello,

It would be nice if `@SuppressWarnings` could be added as a suggestion from php-integrator. 😄 

Cheers

**Comment by Gert-dev** [comment]
Is it by any chance an annotation that is specific to a library or tool?

**Comment by hultberg** [comment]
@Gert-dev As far as I know, maybe. This is a feature for PHPMD [1], while PHPCS has a different tag that pretty much do the same thing [2].

1: https://phpmd.org/documentation/suppress-warnings.html
2: http://stackoverflow.com/a/16071809

**Comment by Gert-dev** [comment]
On one hand, I don't like to include tool-specific things if I can avoid it, but on the other hand, PHPMD and PHPCS are so commonly used and I've already done pretty much the same for Doctrine annotations for the same reason.

**Comment by Gert-dev** [comment]
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.
