### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by ghabxph** [php-integrator/atom-autocompletion#91]
I don't know if it is just me. But php-integrator-completion does not work to me.
I already installed php-integrator-base, and then php-integrator-completion, but it does not even show any single thing.

**Comment by ghabxph** [comment]
Well, clearly, i've done a clear mistake. To all people, please take note of the following.

Make sure you have installed atom-project-manager
Make sure that you have installed php-integrator-base before having php-integrator-autocompletion

That is one ultimate requirement!

Please refer here: https://php-integrator.github.io/#what-do-i-need

Second, you have to setup a project. As far as I know, you have to drag a folder to atom text editor then do the following:

From the menu, go to: Packages > Project Manager > Save Project

After saving the project, Go to Packages > PHP Integrator > Set Up Current Project.

If you have php-integrator-autocompletion installed, then everything will be working now. 👍

Closing the issue now, as it is not really an issue. I'm just trying to get support here. hehe :)

This page shall serve as an additional info for those people who struggle to make this plugin work.

**Comment by ve3** [comment]
I followed every single step on https://php-integrator.github.io/#what-do-i-need but autocomplete is still not working.
just enter `strp` (for `strpos()`) and then still not showing anything.
