### ISSUE TITLE
Feature request: Argument placeholders after function autocompletion

### ISSUE THREAD

**Issue by johnbillion** [php-integrator/atom-autocompletion#94]
PHP Integrator's autocompletion is aware of the available parameters for functions, but it's not very good at guiding you through the parameters once you hit enter or tab. The call-tips and tooltips packages help, but inline parameter placeholders would rock.

I'd love to have the option to hit tab (or enter) after an autocompletion suggestion that populates the function/method arguments in place as placeholders that you can tab through. An example of an existing Atom package which does this is Docblockr.

**Comment by johnbillion** [comment]
The autocomplete-php package does this too: https://atom.io/packages/autocomplete-php

**Comment by Gert-dev** [comment]
Hello. This was actually the case in the past, but I changed the behavior some time ago for reasons explained here [1].

[1] https://github.com/php-integrator/atom-autocompletion/issues/92
