### ISSUE TITLE
Don't follow symlinks when indexing

### ISSUE THREAD

**Issue by nicolasmn** [php-integrator/atom-autocompletion#95]
Cant use autocomplete and call tips since PHP-Integrator is indexing my project forever. The problem is a "symlink loop" I guess.

**Comment by Gert-dev** [comment]
I can't disable this for everyone as there are users that are using symlinking in their codebase. However, do you have a use case for infinitely recursive symlinks in your codebase? Usually symlinks are one-way, but don't point to a folder that somehow references the folder containing the original symlink again.

If so, I'll need to look into adding an option to limit the symlink recursion depth.

**Comment by nicolasmn** [comment]
How about adding a field to PHP-Integrator settings where you can define glob patterns to ignore when indexing?

Also, Atom provides "Ignored Names" and "Follow Symlinks" options in core settings wich could be useful to determine which files/folders to ignore without having to add more settings to PHP-Integrator.

**Comment by Gert-dev** [comment]
Yes, I didn't think of that. That is in fact [already present](https://github.com/php-integrator/atom-base/wiki/Excluding-Folders-From-Indexing). See also [this ticket](https://github.com/php-integrator/atom-base/issues/282) over why I don't use Atom's settings.

**Comment by nicolasmn** [comment]
Thank you, now it works as expected!
