### ISSUE TITLE
Keyword provider priority

### ISSUE THREAD

**Issue by msdm** [php-integrator/atom-autocompletion#96]
I think increasing the priority of the keywordProvider makes the suggestions list more usable. For example, if you want to autocomplete keywords such as "namespace", "class", "abstract", etc. with the current setup, the popup list will suggest them at the end of list, after a lengthy list of classes and global functions names.  This is more annoying particularly for large projects with many dependencies (big "vendor" folder).

My suggestion is to move the keywordProvider declaration right below the snippetsProvider in main.coffee

**Comment by Gert-dev** [comment]
I tested to see if these would interfere with class completions, but that didn't seem to happen. So this has my stamp of approval and I released a new version. Thanks for the suggestion!
