### ISSUE TITLE
Autocompletion stopped working with user defined classes, functions and namespaces in Atom 1.17

### ISSUE THREAD

**Issue by brunoczim** [php-integrator/atom-autocompletion#99]
There are no more suggestions about user defined classes on objects, static members accessing, namespaces, functions... This happened after upgrading Atom to 1.17.

**Comment by Gert-dev** [comment]
Strange, I've only just updated to Atom 1.17, but am not seeing any immediate issues. Did all the other functionalities stop working as well? Are there any errors in the developer tools console?

**Comment by brunoczim** [comment]
I had installed 1.17.0. I downgraded back to 1.16.0 in order to make it work again. After a few days I updated it to 1.17.1 and it is working again.
